apiVersion: v1
kind: Secret
metadata:
  name: feast-data-stores
stringData:
  postgres: |
    host: postgres
    port: 5432
    database: ${POSTGRESQL_DATABASE}
    db_schema: feast
    user: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
  sql: |
    path: postgresql+psycopg://${POSTGRESQL_USER}:${POSTGRESQL_PASSWORD}@postgres:5432/${POSTGRESQL_DATABASE}
    cache_ttl_seconds: 60
    sqlalchemy_config_kwargs:
      echo: false
      pool_pre_ping: true
---
apiVersion: feast.dev/v1alpha1
kind: FeatureStore
metadata:
  name: example
spec:
  feastProject: credit_scoring_local
  feastProjectDir:
    git:
      url: https://github.com/jharmison-redhat/rhoai-feast-demo
      ref: main
  services:
    offlineStore:
      persistence:
        file:
          type: duckdb
      server:
        envFrom:
          - secretRef:
              name: postgres-secret
    onlineStore:
      persistence:
        store:
          type: postgres
          secretRef:
            name: feast-data-stores
      server:
        envFrom:
          - secretRef:
              name: postgres-secret
        env:
          - name: MPLCONFIGDIR
            value: /tmp
    registry:
      local:
        persistence:
          store:
            type: sql
            secretRef:
              name: feast-data-stores
        server:
          restAPI: true
          envFrom:
            - secretRef:
                name: postgres-secret
