apiVersion: v1
kind: Secret
metadata:
  name: feast-data-stores
stringData:
  postgres: |
    host: postgres
    port: 5432
    database: ${POSTGRES_DB}
    db_schema: feast
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  sql: |
    path: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    cache_ttl_seconds: 60
    sqlalchemy_config_kwargs:
        echo: false
        pool_pre_ping: true
---
apiVersion: feast.dev/v1alpha1
kind: FeatureStore
metadata:
  name: example
  namespace: feature-management
spec:
  feastProject: credit_scoring_local
  feastProjectDir:
    git:
      url: https://github.com/jharmison-redhat/rhoai-feast-demo
      ref: main
  services:
    ui:
      envFrom:
        - secretRef:
            name: postgres-secret
    offlineStore:
      persistence:
        file:
          type: duckdb
      server: {}
    onlineStore:
      persistence:
        store:
          type: postgres
          secretRef:
            name: feast-data-stores
      server:
        envFrom:
          - secretRef:
              name: postgres-secret
        env:
          - name: MPLCONFIGDIR
            value: /tmp
    registry:
      local:
        persistence:
          store:
            type: sql
            secretRef:
              name: feast-data-stores
        server:
          logLevel: debug
          restAPI: true
          envFrom:
            - secretRef:
                name: postgres-secret
